# Usage:
# xhost +local:docker && docker compose -f compose.sim.gazebo.yaml up

x-net-config:
  &net-config
  network_mode: host
  ipc: host
  env_file: net.env

x-gpu-config:
  &gpu-config
  runtime: nvidia
  environment:
    - DISPLAY=${DISPLAY:?err}
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all

x-cpu-config:
  &cpu-config
  environment:
    - DISPLAY=${DISPLAY:?err}
    - LIBGL_ALWAYS_SOFTWARE=1

services:
  rosbot-xl:
    image: husarion/rosbot-xl-manipulation-gazebo:humble
    container_name: rosbot_xl_manipulation_simulation
    <<: [ *net-config, *gpu-config ]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot_xl.rviz:/ros2_ws/install/rosbot_xl_manipulation_moveit/share/rosbot_xl_manipulation_moveit/config/moveit.rviz
    command: >
      ros2 launch rosbot_xl_manipulation_gazebo simulation.launch.py
        mecanum:=${MECANUM:-True}
        antenna_rotation_angle:=${ANTENNA_ROTATION_ANGLE:- -1.57}
  
  joy2twist:
    image: husarion/joy2twist:humble-1.0.0-20230204-stable
    <<: *net-config
    devices:
      - /dev/input
    volumes: 
      - ./config/joy2twist.yaml:/joy2twist.yaml
    command: > 
      ros2 launch joy2twist gamepad_controller.launch.py
        joy2twist_params_file:=/joy2twist.yaml