services:
  rviz:
    # Launching rviz with moveit2 requires all the configs, using manipulation simulation image is easiest option
    image: husarion/rosbot-xl:humble-manipulation-simulation
    container_name: rviz
    network_mode: host
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot_xl.rviz:/root/.rviz2/default.rviz
    environment:
      - DDS_CONFIG
      - RMW_IMPLEMENTATION
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=1
    command: ros2 launch rosbot_xl_manipulation_moveit rviz.launch.py

  joy2twist:
    image: husarion/joy2twist:humble-22-12-07
    network_mode: host
    ipc: host
    devices:
      - /dev/input
    volumes: 
      - ./config/joy2twist.yaml:/joy2twist.yaml
    environment:
      - DDS_CONFIG
      - RMW_IMPLEMENTATION
    command: > 
      ros2 launch joy2twist gamepad_controller.launch.py
        joy2twist_params_file:=/joy2twist.yaml

