services:
  rosbot-xl:
    image: husarion/rosbot-xl-manipulation:humble
    network_mode: host
    ipc: host
    devices:
      - ${MANIPULATOR_SERIAL:?err}:/dev/manipulator
    volumes: 
      - ./config/joy_servo.yaml:/joy_servo.yaml
    environment:
      - DDS_CONFIG
      - RMW_IMPLEMENTATION
    command: >
      ros2 launch rosbot_xl_manipulation_bringup bringup.launch.py mecanum:=${MECANUM:-True}
        manipulator_usb_port:=/dev/manipulator
        manipulator_baud_rate:=${MANIPULATOR_BAUDRATE:-115200}
        joy_servo_params_file:=/joy_servo.yaml
        antenna_rotation_angle:=-1.57

  microros:
    image: husarion/micro-ros-agent:humble-3.1.2-20230204-stable
    network_mode: host
    ipc: host
    environment:
      - DDS_CONFIG
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    command: ros2 run micro_ros_agent micro_ros_agent udp4 --port 8888
