# Quick Start
# $ xhost local:root
# $ docker compose -f compose.sim.nvidia.yaml up

services:
  rosbot-xl:
    image: husarion/rosbot-xl-manipulation-gazebo:humble
    container_name: rosbot_xl_manipulation_simulation
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    ipc: host
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}
    command: ros2 launch rosbot_xl_manipulation_gazebo simulation.launch.py mecanum:=${MECANUM:-True}
  
  joy2twist:
    image: husarion/joy2twist:humble-1.0.0-20230204-stable
    network_mode: host
    ipc: host
    devices:
      - /dev/input
    volumes: 
      - ./config/joy2twist.yaml:/joy2twist.yaml
    environment:
      - DDS_CONFIG
      - RMW_IMPLEMENTATION
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
    command: > 
      ros2 launch joy2twist gamepad_controller.launch.py
        joy2twist_params_file:=/joy2twist.yaml
