# Quick Start
# $ xhost local:root
# $ docker compose -f compose.pc.yaml up

services:
  rviz:
    # Launching rviz with moveit2 requires all the configs, using manipulation simulation image is easiest option
    image: husarion/rosbot-xl-manipulation-gazebo:humble-open_manipulator_x
    container_name: rviz
    network_mode: host
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot_xl.rviz:/ros2_ws/install/rosbot_xl_manipulation_moveit/share/rosbot_xl_manipulation_moveit/config/moveit.rviz
    runtime: nvidia
    environment:
      - DDS_CONFIG
      - RMW_IMPLEMENTATION
      - DISPLAY=${DISPLAY:?err}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    command: ros2 launch rosbot_xl_manipulation_moveit rviz.launch.py

  joy2twist:
    image: husarion/joy2twist:humble-1.0.0-20230204-stable
    network_mode: host
    ipc: host
    devices:
      - /dev/input
    volumes: 
      - ./config/joy2twist.yaml:/joy2twist.yaml
    environment:
      - DDS_CONFIG
      - RMW_IMPLEMENTATION
    command: > 
      ros2 launch joy2twist gamepad_controller.launch.py
        joy2twist_params_file:=/joy2twist.yaml

