services:
  rosbot-xl:
    image: husarion/rosbot-xl:humble-manipulator
    network_mode: host
    ipc: host
    devices:
      - ${MANIPULATOR_SERIAL:-/dev/ttyUSB0}:/dev/manipulator
    environment:
      - DDS_CONFIG
      - RMW_IMPLEMENTATION
    command: >
      ros2 launch rosbot_xl_bringup bringup.launch.py mecanum:=${MECANUM:-True}
        manipulator_usb_port:=/dev/manipulator
        manipulator_baud_rate:=${MANIPULATOR_BAUDRATE:-115200}

  microros:
    image: husarion/micro-ros-agent:humble-22-12-07
    network_mode: host
    ipc: host
    environment:
      - DDS_CONFIG
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    command: ros2 run micro_ros_agent micro_ros_agent udp4 --port 8888

  rplidar:
    image: husarion/rplidar:humble-22-12-07
    network_mode: host
    ipc: host
    devices:
      - ${LIDAR_SERIAL:?err}:/dev/ttyUSB0
    environment:
      - DDS_CONFIG
      - RMW_IMPLEMENTATION
    command: ros2 launch sllidar_ros2 sllidar_launch.py serial_baudrate:=${LIDAR_BAUDRATE:-115200}
